### ISSUE TITLE
Failed to start service after upgrade to lidar-0.8.0.2042-2.el8

### ISSUE THREAD

**Issue by tim427** [negativo17/lidarr#1]
Since version 'lidar-0.8.0.2042-2.el8' the service isn't able to start with the following error "Failed to create CoreCLR, HRESULT: 0x80004005"

Rollback to 'lidarr-0.8.0.2042-1.el8.noarch' works without an issue!

Also manual starting, works without an issue; `sudo -u lidarr /usr/lib64/lidarr/Lidarr -nobrowser -data /var/lib/lidarr`

Log entries;
```
Mar 12 12:19:11 downloadmachine systemd[1]: Started Automated manager and downloader for Music.
-- Subject: Unit lidarr.service has finished start-up
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
--
-- Unit lidarr.service has finished starting up.
--
-- The start-up result is done.
Mar 12 12:19:11 downloadmachine systemd[1]: lidarr.service: Main process exited, code=exited, status=137/n/a
Mar 12 12:19:11 downloadmachine systemd[1]: lidarr.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
--
-- The unit lidarr.service has entered the 'failed' state with result 'exit-code'.
```

PS; Same happend with https://github.com/negativo17/radarr/

**Comment by scaronni** [comment]
Unfortunately when switching from Mono to .NET, many SELinux policies are required. One option is to disable SELinux, another is to enable the proper booleans and correctly label all your music library. In the latest update there is also a separte `lidarr-selinux` package installed automatically to provide the basic policy.

```
# getsebool -a | grep lidarr
lidarr_access_all_ro --> off
lidarr_access_all_rw --> off
lidarr_access_home_dirs_rw --> off
lidarr_anon_write --> off
lidarr_list_all_dirs --> on
lidarr_send_email --> off
lidarr_sys_cert_ro --> off
```
Setting `setsebool -P lidarr_access_all_rw=on` should be enough to get you going to the previous state (i.e. unconfined service where permissions are enforced by actual permissions on files).
