### ISSUE TITLE
Runtime Config

### ISSUE THREAD

**Issue by tim427** [negativo17/lidarr#2]
```
[root@ downloadmachine ~]# /usr/lib64/lidarr/Lidarr -nobrowser -data /var/lib/lidarr
It was not possible to find any compatible framework version
The framework 'Microsoft.AspNetCore.App', version '3.1.14' was not found.
  - The following frameworks were found:
      3.1.13 at [/usr/lib64/dotnet/shared/Microsoft.AspNetCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=3.1.14&arch=x64&rid=centos.8-x64
```

After inspection, I was able to start the service, by replacing; `"version": "3.1.14"` to `"version": "3.1.13"` in the `/usr/lib64/lidarr/Lidarr.runtimeconfig.json`-file.

I'm currently investigating what actually creates the `Lidarr.runtimeconfig.json`-file, and why the version is one version off.

**Comment by scaronni** [comment]
Argh, the update got pushed after i built it probably. I need to make sure only the major version is set in the file.

Thanks,
--Simone

**Comment by scaronni** [comment]
OK, not easy to do, I will leave the build from source but still the fat binary with the bundled runtime as their releases. New update in a couple of hours.
